// Version updater
package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

func main() {
	tag := run("git", "describe", "--tags", "--abbrev=0")
	commit := run("git", "rev-parse", "--short", "HEAD")
	date := time.Now().UTC().Format(time.RFC3339)

	content := fmt.Sprintf(`// Package version contains version information. Auto-generated by update_version.go, DO NOT EDIT
package version

var (
	Version   = "%s"
	Commit    = "%s"
	BuildDate = "%s"
)
`, tag, commit, date)
	versionPath := "src/internal/version/version.go"
	err := os.WriteFile(versionPath, []byte(content), 0644)
	if err != nil {
		panic(err)
	}
}

func run(cmd string, args ...string) string {
	out, err := exec.Command(cmd, args...).Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}
