// Package version contains version information. Auto-generated by update_version.go, DO NOT EDIT
package version

var (
	Version   = "0.1.0"
	Commit    = "0eb135b"
	BuildDate = "2025-09-16T15:58:05Z"
)
